In [29]:
import librosa
import os 
import numpy as np 
import matplotlib.pyplot as plt 
import librosa.display
import pandas as pd
import random

In [3]:
playlist_titles = os.listdir('sample_playlist')

In [ ]:
playlist_dict = {}

Loading the playlist up 

In [15]:
#for now hardcode the sr 
sr=22050

for i in playlist_titles:
    y,sr=librosa.load(f'sample_playlist/{i}')
    playlist_dict[i] = y 

Taking 30 random 5 second samples

In [ ]:
#aa = audio array also use y elsewhere
aa = playlist_dict['51 Days - Paper Moon.mp3']
song_length = librosa.get_duration(y=aa,sr=sr)
#rtl = random timestamp list
samples = np.random.randint(0,int(song_length-5),30)
samples_range = np.column_stack((samples,samples+5))

segments = []
for j in samples_range:
    start_time = j[0] * sr
    end_time = j[1] * sr
    segment_j = aa[start_time:end_time] 
    segments.append(segment_j)

In [74]:
segments

[array([0.00193176, 0.00464286, 0.00713604, ..., 0.16253081, 0.1663679 ,
        0.17008427], shape=(110250,), dtype=float32),
 array([0.09638751, 0.10564822, 0.10876971, ..., 0.06124226, 0.0705295 ,
        0.07253388], shape=(110250,), dtype=float32),
 array([-0.02334119, -0.01433915,  0.00247769, ..., -0.10553225,
        -0.09018347, -0.06741425], shape=(110250,), dtype=float32),
 array([0.06979663, 0.10841719, 0.07657804, ..., 0.14719291, 0.14054984,
        0.13930571], shape=(110250,), dtype=float32),
 array([-0.12309765, -0.17744812, -0.23085794, ..., -0.03416098,
        -0.03023769,  0.00257601], shape=(110250,), dtype=float32),
 array([ 0.03701511,  0.04087679,  0.04206615, ..., -0.15401714,
        -0.16490094, -0.16007645], shape=(110250,), dtype=float32),
 array([0.2813436 , 0.26489744, 0.28296903, ..., 0.21577826, 0.22528215,
        0.25623032], shape=(110250,), dtype=float32),
 array([-0.00737547,  0.00148875, -0.00971846, ..., -0.04084542,
         0.0038065 , -0.0316